// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY3ByMuzJ4rtJZrmxOwicYdSUnXexwqko',
    appId: '1:557964528207:web:cb2ea845e4e185e33ef83a',
    messagingSenderId: '557964528207',
    projectId: 'signio-d6525',
    authDomain: 'signio-d6525.firebaseapp.com',
    storageBucket: 'signio-d6525.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe651u1T0mAf-xBa_U1iCHAHTdqy2jWHs',
    appId: '1:557964528207:android:9f3961ba439902803ef83a',
    messagingSenderId: '557964528207',
    projectId: 'signio-d6525',
    storageBucket: 'signio-d6525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGrDy9wOMILEXv1tgUKTwT92KxdoCmDw',
    appId: '1:557964528207:ios:a470eefb4b96a2213ef83a',
    messagingSenderId: '557964528207',
    projectId: 'signio-d6525',
    storageBucket: 'signio-d6525.appspot.com',
    iosBundleId: 'com.example.untitled18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGrDy9wOMILEXv1tgUKTwT92KxdoCmDw',
    appId: '1:557964528207:ios:daf4ec37bd9a593f3ef83a',
    messagingSenderId: '557964528207',
    projectId: 'signio-d6525',
    storageBucket: 'signio-d6525.appspot.com',
    iosBundleId: 'com.example.untitled18.RunnerTests',
  );
}
